const randomId = () => Math.random().toString(36).substring(2, 9);

export const users = [
  {
    id: randomId() + "home",
    firstname: "Teressiah ",
    lastname: "Ngomi",
    username: "Home",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "social@gmail.com",
  },
  {
    id: randomId() + "your",
    firstname: "james ",
    lastname: "hy",
    username: "YourVideos",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "social@gmail.com",
  },
  {
    id: randomId() + "saved",
    firstname: "JMark ",
    lastname: "l",
    username: "SavedVideos",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "social@gmail.com",
  },

  {
    id: randomId() + "book",
    firstname: "Kim ",
    lastname: "ert",
    username: "BookedGigs",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "herri@yahoo.ke",
  },
  {
    id: randomId() + "chats",
    firstname: "TereGracessiah ",
    lastname: "sam",
    username: "Chats",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "chat@outlook.com",
  },

  {
    id: randomId() + "profile",
    firstname: "james ",
    lastname: "manny",
    username: "UpdateProfile",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "profile@gmail.com",
  },

  {
    id: randomId() + "about",
    firstname: "trey ",
    lastname: "yng",
    username: "AbouUs",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "aboutm2@gmail.com",
  },
  {
    id: randomId() + "contact",
    firstname: "yuri ",
    lastname: "tui",
    username: "Contactus",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "contactus@go.ke",
  },

  {
    id: randomId() + "rating",
    firstname: "reah ",
    lastname: "Ngomi",
    username: "Reviews",
    profileimage: "./assets/prof3.jpg",
    instrument: "piano",
    experience: "2 and a half year",
    city: "Nairobi",
    email: "assets@gmail.com",
    showRating: () => {
      console.log("notifications");
    },
  },
];
export const posts = [
  {
    id: randomId() + 1,
    postedBy: {
      id: randomId() + 1,
      firstname: "Teressiah ",
      lastname: "Ngomi",
      username: "jane123",
      profileimage: "./assets/images/kemal.jpg",
      username: "zacharia123",
      photoUrl: "./assets/images/logo-no-background.png",
      instrument: "piano",
      experience: "2 and a half year",
      city: "Nairobi",
    },
    content:
      "Ive always loved trying something new and lately i have been testing react native so far i love it.I just need to learn how to integrate with mongodb for my datbase etc",
    title: "Exploring the beauty of nature! 🌳🌼",
    likes: ["muid", "fg", "bg", "dd", "em", "en"],
    comments: [
      {
        id: randomId() + 1,
        postedBy: {
          id: randomId() + 1,
          name: "Janemith Kamau",
          username: "jane123",
          profileimage: "./assets/prof3.jpg",
          instrument: "piano",
          experience: "2 and a half year",
          city: "Nairobi",
        },
        text: "Wow, this is so beautiful!",
        createdAt: "2024-11-21T10:15:00Z",
      },
      {
        id: randomId() + 2,
        postedBy: {
          id: randomId() + 1,
          firstname: "Liam ",
          lastname: "Ngomi",
          username: "zach123",
          profileimage: "./assets/images/kemal.jpg",
          username: "zachaia123",
          photoUrl: "./assets/images/logo-no-background.png",
          instrument: "piano",
          experience: "2 and a half year",
          city: "Nairobi",
        },
        text: "Where was this taken?",
        createdAt: "2024-11-21T10:20:00Z",
      },
    ],
    createdAt: "2024-11-20T09:00:00Z",
  },
  {
    id: randomId() + 2,
    postedBy: {
      id: randomId() + 1,
      firstname: "Teressiah ",
      lastname: "Ngomi",
      username: "jane123",
      profileimage: "./assets/images/kemal.jpg",
      username: "jane123",
      profileimage: "./assets/prof3.jpg",
      instrument: "piano",
      experience: "2 and a half year",
      city: "Nairobi",
    },
    content:
      "Ive always loved trying something new and lately i have been testing react native so far i love it.I just need to learn how to integrate with mongodb for my datbase etc",
    title: "Just finished my first marathon! 🏃‍♀️💪",
    likes: [
      "muid",
      "fg",
      "bg",
      "dd",
      "em",
      "e445fdfn",
      "ddfdfdfd4",
      "efd545dfdfn",
    ],
    comments: [
      {
        id: randomId() + 1,
        postedBy: {
          id: randomId() + 1,
          firstname: "Teressiah ",
          lastname: "Ngomi",
          username: "jane123",
          profileimage: "./assets/images/kemal.jpg",
        },
        text: "Congratulations! That’s amazing!",
        createdAt: "2024-11-21T11:00:00Z",
      },
      {
        id: randomId() + 2,
        postedBy: {
          id: randomId() + 1,
          name: "Janemith Kamau",
          username: "jane123",
          profileimage: "./assets/prof3.jpg",
          instrument: "piano",
          experience: "2 and a half year",
          city: "Nairobi",
        },
        text: "You’re an inspiration!",
        createdAt: "2024-11-21T11:10:00Z",
      },
    ],
    createdAt: "2024-11-20T10:30:00Z",
  },
  {
    id: randomId() + 3,
    postedBy: {
      id: randomId() + 1,
      firstname: "Teressiah ",
      lastname: "Ngomi",
      username: "jane123",
      profileimage: "./assets/images/kemal.jpg",
      username: "maisee1234",
      profileimage: "./assets/prof3.jpg",
      instrument: "piano",
      experience: "2 and a half year",
      city: "Nairobi",
    },
    content:
      "Ive always loved trying something new and lately i have been testing react native so far i love it.I just need to learn how to integrate with mongodb for my datbase etc",
    title: "AI is revolutionizing the world as we know it. Thoughts? 🤖",
    likes: [
      "muyid",
      "fg",
      "bg",
      "dd",
      "em",
      "en",
      "drrd",
      "eeeeem",
      "e2323sdn",
    ],
    comments: [
      {
        id: randomId() + 1,
        postedBy: {
          id: randomId() + 1,
          name: "Ian Kamau",
          username: "jane123",
          photoUrl: "./assets/icon.png",
        },
        text: "Totally agree! It’s fascinating!",
        createdAt: "2024-11-21T12:00:00Z",
      },
      {
        id: randomId() + 2,
        postedBy: {
          id: randomId() + 1,
          name: "Mwas Iano Kamau",
          username: "jane123",
          photoUrl: "./assets/images/hero2.jpg",
        },
        text: "But what about the risks?",
        createdAt: "2024-11-21T12:15:00Z",
      },
    ],
    createdAt: "2024-11-20T15:00:00Z",
  },
];
